/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/vis/verbose 0

/rat/db/set DETECTOR experiment "enrg"
/rat/db/set DETECTOR geo_file "enrg/enrg_3t.geo"

/run/initialize

/process/activate Cerenkov all
/glg4scint/on

/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton
/tracking/discardParticleTrajectory e-

################################ VISUALIZATION ##########################
#initialize the visualizer
/vis/open OGLIQt 10000
/vis/scene/create
/vis/scene/add/volume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
/vis/drawVolume

/vis/viewer/set/viewpointVector 0.0 0.0001 1
/vis/viewer/zoom 2
/vis/viewer/set/upVector 0 0 1

################################################################

#####################
# BEGIN EVENT LOOP

/rat/proc simpledaq
#/rat/proc fitbonsai
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"

# Use IO.default_output_filename
/rat/proclast outroot

##### Single particles ######
/generator/add combo gun:point
/generator/pos/set 0.0 0.0 0.0
/generator/vtx/set e+ 0 0 0 2
######################

##### IBD ######
#/generator/add combo reacibd:fill 
#/generator/reacibd/U235 0.56
#/generator/reacibd/U238 0.08
#/generator/reacibd/Pu239 0.30
#/generator/reacibd/Pu241 0.06
#/generator/vtx/set 1.0 0.0 0.0
#/generator/pos/set 0.0 0.0 0.0
######################


/run/beamOn 1000

#END EVENT LOOP
#####################

/vis/viewer/refresh
#/vis/viewer/flush




